name: message_cipher
description: A Polymer Dart application that translates messages using a customizable (in code) cipher.
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
