name: message_cipher
description: A Polymer Dart application that translates messages using a customizable (in code) cipher.
dependencies:
  polymer: ">=0.11.0-dev.4"
transformers:
- polymer:
    entry_points: web/index.html
